[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    tzapu/WiFiManager@^2.0.17
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -I include
