[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_flags =
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
monitor_speed = 115200
